version: '3.8'
services:
  ChatBot:
    image: llmtornadoa2aagentserver:latest
    ports:
      - "44225:8080"
    volumes:
      - C:\Users\johnl\source\AgentDockerMount:/app/output

  Chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
